#!/bin/sh
#
# openstack-neat-local-manager  OpenStack Neat Local Manager
#
# chkconfig:   - 99 01
# description: The local manager periodically reads the data \
#              stored by the data collector and using the    \
#              specified in the configuration algorithms     \
#              determines whether the host is underloaded or \
#              overloaded. Then it sends the appropriate     \
#              messages to the global manager.        

### BEGIN INIT INFO
# Provides: openstack_neat_local_manager
# Required-Start: $remote_fs $network $syslog openstack_neat_data_collector
# Required-Stop: $remote_fs $network $syslog
# Short-Description: OpenStack Neat Local Manager
# Description: The local manager periodically reads the data 
#              stored by the data collector and using the    
#              specified in the configuration algorithms     
#              determines whether the host is underloaded or 
#              overloaded. Then it sends the appropriate     
#              messages to the global manager.
### END INIT INFO

. /etc/rc.d/init.d/functions

suffix=local-manager
prog=openstack-neat-$suffix
exec="/usr/bin/neat-$suffix"
piddir="/var/run/neat"
pidfile="$piddir/neat-$suffix.pid"
logdir="/var/log/neat"
logfile="$logdir/local-manager-service.log"

[ -e /etc/sysconfig/$prog ] && . /etc/sysconfig/$prog

lockfile=/var/lock/subsys/$prog

start() {
    [ -x $exec ] || exit 5
    [ -f $config ] || exit 6
    echo -n $"Starting $prog: "
    mkdir -p $piddir
    mkdir -p $logdir
    daemon --user root --pidfile $pidfile "$exec &>$logfile & echo \$! > $pidfile"
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile
    return $retval
}

stop() {
    echo -n $"Stopping $prog: "
    killproc -p $pidfile $prog
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

restart() {
    stop
    start
}

reload() {
    restart
}

force_reload() {
    restart
}

rh_status() {
    status -p $pidfile $prog
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}


case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    restart)
        $1
        ;;
    reload)
        rh_status_q || exit 7
        $1
        ;;
    force-reload)
        force_reload
        ;;
    status)
        rh_status
        ;;
    condrestart|try-restart)
        rh_status_q || exit 0
        restart
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload}"
        exit 2
esac
exit $?
